# Generated by Django 5.1.6 on 2025-04-20 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiteruser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruiterUser',
            new_name='Recruiter',
        ),
    ]
